┏━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃[1m   [22m┃[1m Name    [22m┃[1m Type          [22m┃[1m Params [22m┃
┡━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━┩
│ 0 │ encoder │ ResNetEncoder │ 11.2 M │
│ 1 │ decoder │ ResNetDecoder │  8.6 M │
│ 2 │ fc      │ Linear        │  131 K │
└───┴─────────┴───────────────┴────────┘
[1mTrainable params[22m: 19.9 M
[1mNon-trainable params[22m: 0
[1mTotal params[22m: 19.9 M
[1mTotal estimated model params size (MB)[22m: 79
[?25h
GPU available: True, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/configuration_validator.py:386: LightningDeprecationWarning: The `Callback.on_epoch_end` hook was deprecated in v1.6 and will be removed in v1.8. Please use `Callback.on_<train/validation/test>_epoch_end` instead.
  f"The `Callback.{hook}` hook was deprecated in v1.6 and"
Traceback (most recent call last):
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/einops/einops.py", line 410, in reduce
    return _apply_recipe(recipe, tensor, reduction_type=reduction)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/einops/einops.py", line 233, in _apply_recipe
    _reconstruct_from_shape(recipe, backend.shape(tensor))
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/einops/einops.py", line 163, in _reconstruct_from_shape_uncached
    raise EinopsError('Expected {} dimensions, got {}'.format(len(self.input_composite_axes), len(shape)))
einops.EinopsError: Expected 5 dimensions, got 4
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "train.py", line 335, in <module>
    main(args)
  File "train.py", line 299, in main
    dm.val_dataloader(),
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 769, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run
    results = self._run_stage()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_train
    self._run_sanity_check()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1411, in _run_sanity_check
    val_loop.run()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 153, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 111, in advance
    batch = next(data_fetcher)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
    return self.fetching_function()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/utilities/fetching.py", line 259, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/utilities/fetching.py", line 273, in _fetch_next_batch
    batch = next(iterator)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 363, in __getitem__
    return self.dataset[self.indices[idx]]
  File "train.py", line 174, in __getitem__
    'vision': rearrange(self.vision[idx], 'b num_stack h w c -> b (num_stack c) h w'),
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/einops/einops.py", line 487, in rearrange
    return reduce(tensor, pattern, reduction='rearrange', **axes_lengths)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/einops/einops.py", line 418, in reduce
    raise EinopsError(message + '\n {}'.format(e))
einops.EinopsError:  Error while processing rearrange-reduction pattern "b num_stack h w c -> b (num_stack c) h w".
 Input tensor shape: torch.Size([1, 15, 15, 3]). Additional info: {}.
 Expected 5 dimensions, got 4
Traceback (most recent call last):
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/einops/einops.py", line 410, in reduce
    return _apply_recipe(recipe, tensor, reduction_type=reduction)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/einops/einops.py", line 233, in _apply_recipe
    _reconstruct_from_shape(recipe, backend.shape(tensor))
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/einops/einops.py", line 163, in _reconstruct_from_shape_uncached
    raise EinopsError('Expected {} dimensions, got {}'.format(len(self.input_composite_axes), len(shape)))
einops.EinopsError: Expected 5 dimensions, got 4
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "train.py", line 335, in <module>
    main(args)
  File "train.py", line 299, in main
    dm.val_dataloader(),
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 769, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run
    results = self._run_stage()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_train
    self._run_sanity_check()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1411, in _run_sanity_check
    val_loop.run()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 153, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 111, in advance
    batch = next(data_fetcher)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
    return self.fetching_function()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/utilities/fetching.py", line 259, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/pytorch_lightning/utilities/fetching.py", line 273, in _fetch_next_batch
    batch = next(iterator)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 363, in __getitem__
    return self.dataset[self.indices[idx]]
  File "train.py", line 174, in __getitem__
    'vision': rearrange(self.vision[idx], 'b num_stack h w c -> b (num_stack c) h w'),
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/einops/einops.py", line 487, in rearrange
    return reduce(tensor, pattern, reduction='rearrange', **axes_lengths)
  File "/home/mila/s/sonnery.hugo/.conda/envs/env-rl-training/lib/python3.7/site-packages/einops/einops.py", line 418, in reduce
    raise EinopsError(message + '\n {}'.format(e))
einops.EinopsError:  Error while processing rearrange-reduction pattern "b num_stack h w c -> b (num_stack c) h w".
 Input tensor shape: torch.Size([1, 15, 15, 3]). Additional info: {}.
